
export const GET_MOVIES_API='GET_MOVIES_API'; 

export const SET_MOVIE_SHOWING='SET_MOVIE_SHOWING'
export const SET_MOVIE_COMINGSOON='SET_MOVIE_COMINGSOON'

export const GET_MOVIES_LIMIT_API='GET_MOVIES_LIMIT_API'